### ISSUE TITLE
Docs on how to declare indexes

### ISSUE THREAD

**Issue by iBobik** [skorokithakis/goatfish#6]
Hello,
I am lost what this means:
```
        indexes = (
            ("foo",),
            ("foo", "bar"),
        )
```

I does not know why first line has only foo, and second has bar also.

Why bar is in indexes when in examples considered as not index (slow `Test.find(bar="hello")`).

Would be nice to describe exactly structure of this configuration.

**Comment by skorokithakis** [comment]
That's because the second index can only use both fields, and not just one. I will clarify that, thanks!

**Comment by iBobik** [comment]
Another question to clarify: Why I would like to have more than one field in an index? :-)

**Comment by skorokithakis** [comment]
Because then it's much faster to search by both fields? :P
