### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by sam2332** [skorokithakis/goatfish#9]
On a fresh install, i am getting the following error

I used pip to install the module

**Comment by sam2332** [comment]
Collecting goatfish
  Downloading goatfish-0.1.tar.gz (2.6 kB)
Building wheels for collected packages: goatfish
  Building wheel for goatfish (setup.py): started
  Building wheel for goatfish (setup.py): finished with status 'done'
  Created wheel for goatfish: filename=goatfish-0.1-py3-none-any.whl size=3369 sha256=1018424ea239f49d54060f3bf661bbaaca534feed07eba274ff65f04d598981a
  Stored in directory: c:\users\srudloff\appdata\local\pip\cache\wheels\da\50\35\cb6086c255e14ea913b76f52c676ff35c29da7244a934770d0
Successfully built goatfish
Installing collected packages: goatfish
Successfully installed goatfish-0.1

**Comment by skorokithakis** [comment]
This is correct, there is no module named "models". Where did you see this module?

**Comment by skorokithakis** [comment]
It will not, since there is no module like that. Can you post your code?

**Comment by sam2332** [comment]
all i did was copy the example code from github after installing the pypy package without a version number

I have resolved this with the following command

`pip install goatfish==2.0.0a0`

**Comment by skorokithakis** [comment]
Oh hmm, yes, version 2 is different. The package is in a bit of a transitional period, as JSON support in SQLite greatly simplified the implementation, but I'm afraid the docs haven't kept up.

**Comment by sam2332** [comment]
ahh okay, thank you :)
